/*
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.toolbox.client.model.ProcessKeepLogs;
import io.daytona.toolbox.client.model.ProcessKind;
import io.daytona.toolbox.client.model.ProcessShellSelector;
import io.daytona.toolbox.client.model.ProcessStdinMode;
import io.daytona.toolbox.client.model.ProcessTerminalSize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateProcessRequest
 */
public class CreateProcessRequestTest {
    private final CreateProcessRequest model = new CreateProcessRequest();

    /**
     * Model tests for CreateProcessRequest
     */
    @Test
    public void testCreateProcessRequest() {
        // TODO: test CreateProcessRequest
    }

    /**
     * Test the property 'argv'
     */
    @Test
    public void argvTest() {
        // TODO: test argv
    }

    /**
     * Test the property 'cwd'
     */
    @Test
    public void cwdTest() {
        // TODO: test cwd
    }

    /**
     * Test the property 'env'
     */
    @Test
    public void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'keepLogs'
     */
    @Test
    public void keepLogsTest() {
        // TODO: test keepLogs
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'shell'
     */
    @Test
    public void shellTest() {
        // TODO: test shell
    }

    /**
     * Test the property 'shellCommand'
     */
    @Test
    public void shellCommandTest() {
        // TODO: test shellCommand
    }

    /**
     * Test the property 'stdin'
     */
    @Test
    public void stdinTest() {
        // TODO: test stdin
    }

    /**
     * Test the property 'terminal'
     */
    @Test
    public void terminalTest() {
        // TODO: test terminal
    }

    /**
     * Test the property 'timeoutMs'
     */
    @Test
    public void timeoutMsTest() {
        // TODO: test timeoutMs
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
