/*
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.toolbox.client.model.SessionKernel;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateProcessSessionRequest
 */
public class CreateProcessSessionRequestTest {
    private final CreateProcessSessionRequest model = new CreateProcessSessionRequest();

    /**
     * Model tests for CreateProcessSessionRequest
     */
    @Test
    public void testCreateProcessSessionRequest() {
        // TODO: test CreateProcessSessionRequest
    }

    /**
     * Test the property 'cwd'
     */
    @Test
    public void cwdTest() {
        // TODO: test cwd
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kernel'
     */
    @Test
    public void kernelTest() {
        // TODO: test kernel
    }

}
