/*
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.toolbox.client.model.ProcessKeepLogs;
import io.daytona.toolbox.client.model.ProcessKind;
import io.daytona.toolbox.client.model.ProcessShellSelector;
import io.daytona.toolbox.client.model.ProcessState;
import io.daytona.toolbox.client.model.ProcessStdinMode;
import io.daytona.toolbox.client.model.ProcessTerminalReason;
import io.daytona.toolbox.client.model.ProcessTerminalSize;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Process
 */
public class ProcessTest {
    private final Process model = new Process();

    /**
     * Model tests for Process
     */
    @Test
    public void testProcess() {
        // TODO: test Process
    }

    /**
     * Test the property 'argv'
     */
    @Test
    public void argvTest() {
        // TODO: test argv
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'cwd'
     */
    @Test
    public void cwdTest() {
        // TODO: test cwd
    }

    /**
     * Test the property 'env'
     */
    @Test
    public void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'exitCode'
     */
    @Test
    public void exitCodeTest() {
        // TODO: test exitCode
    }

    /**
     * Test the property 'exitedAt'
     */
    @Test
    public void exitedAtTest() {
        // TODO: test exitedAt
    }

    /**
     * Test the property 'firstAvailableCursor'
     */
    @Test
    public void firstAvailableCursorTest() {
        // TODO: test firstAvailableCursor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'keepLogs'
     */
    @Test
    public void keepLogsTest() {
        // TODO: test keepLogs
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'lastCursor'
     */
    @Test
    public void lastCursorTest() {
        // TODO: test lastCursor
    }

    /**
     * Test the property 'legacyCommandId'
     */
    @Test
    public void legacyCommandIdTest() {
        // TODO: test legacyCommandId
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pid'
     */
    @Test
    public void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'resolvedShell'
     */
    @Test
    public void resolvedShellTest() {
        // TODO: test resolvedShell
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'shell'
     */
    @Test
    public void shellTest() {
        // TODO: test shell
    }

    /**
     * Test the property 'shellCommand'
     */
    @Test
    public void shellCommandTest() {
        // TODO: test shellCommand
    }

    /**
     * Test the property 'signal'
     */
    @Test
    public void signalTest() {
        // TODO: test signal
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stdin'
     */
    @Test
    public void stdinTest() {
        // TODO: test stdin
    }

    /**
     * Test the property 'system'
     */
    @Test
    public void systemTest() {
        // TODO: test system
    }

    /**
     * Test the property 'terminal'
     */
    @Test
    public void terminalTest() {
        // TODO: test terminal
    }

    /**
     * Test the property 'timeoutMs'
     */
    @Test
    public void timeoutMsTest() {
        // TODO: test timeoutMs
    }

    /**
     * Test the property 'truncatedHead'
     */
    @Test
    public void truncatedHeadTest() {
        // TODO: test truncatedHead
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
