/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BlockmountConflict
 */
public class BlockmountConflictTest {
    private final BlockmountConflict model = new BlockmountConflict();

    /**
     * Model tests for BlockmountConflict
     */
    @Test
    public void testBlockmountConflict() {
        // TODO: test BlockmountConflict
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'winner'
     */
    @Test
    public void winnerTest() {
        // TODO: test winner
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'oursSha'
     */
    @Test
    public void oursShaTest() {
        // TODO: test oursSha
    }

    /**
     * Test the property 'theirsSha'
     */
    @Test
    public void theirsShaTest() {
        // TODO: test theirsSha
    }

}
