/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.api.client.model.GpuCapacity;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GpuCapacityResponse
 */
public class GpuCapacityResponseTest {
    private final GpuCapacityResponse model = new GpuCapacityResponse();

    /**
     * Model tests for GpuCapacityResponse
     */
    @Test
    public void testGpuCapacityResponse() {
        // TODO: test GpuCapacityResponse
    }

    /**
     * Test the property 'observedAt'
     */
    @Test
    public void observedAtTest() {
        // TODO: test observedAt
    }

    /**
     * Test the property 'capacity'
     */
    @Test
    public void capacityTest() {
        // TODO: test capacity
    }

}
