/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IntFilter
 */
public class IntFilterTest {
    private final IntFilter model = new IntFilter();

    /**
     * Model tests for IntFilter
     */
    @Test
    public void testIntFilter() {
        // TODO: test IntFilter
    }

    /**
     * Test the property 'eq'
     */
    @Test
    public void eqTest() {
        // TODO: test eq
    }

    /**
     * Test the property 'not'
     */
    @Test
    public void notTest() {
        // TODO: test not
    }

    /**
     * Test the property 'in'
     */
    @Test
    public void inTest() {
        // TODO: test in
    }

    /**
     * Test the property 'notIn'
     */
    @Test
    public void notInTest() {
        // TODO: test notIn
    }

    /**
     * Test the property 'gte'
     */
    @Test
    public void gteTest() {
        // TODO: test gte
    }

    /**
     * Test the property 'lte'
     */
    @Test
    public void lteTest() {
        // TODO: test lte
    }

    /**
     * Test the property 'gt'
     */
    @Test
    public void gtTest() {
        // TODO: test gt
    }

    /**
     * Test the property 'lt'
     */
    @Test
    public void ltTest() {
        // TODO: test lt
    }

}
