version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /.github/actions/setup-toolchain
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: npm
    directories:
      - /
      - /sdk-typescript
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-prod:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: pip
    directories:
      - /sdk-python
      - /api-client-python
      - /api-client-python-async
      - /toolbox-api-client-python
      - /toolbox-api-client-python-async
      - /analytics-api-client-python
      - /analytics-api-client-python-async
    schedule:
      interval: weekly
      day: monday
    groups:
      pip-prod:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: gomod
    directories:
      - /cli
      - /api-client-go
      - /sdk-go
      - /toolbox-api-client-go
    schedule:
      interval: weekly
      day: monday
    groups:
      gomod-prod:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "chore(deps)"
