header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Daytona Platforms Inc.
    content: |
      Copyright Daytona Platforms Inc.
      SPDX-License-Identifier: Apache-2.0
    pattern: |
      Copyright (\d{4} )?Daytona Platforms Inc\.
      SPDX-License-Identifier: Apache-2\.0
  paths:
    - 'cli/**/*.go'
    - 'cli/**/*.sh'
    - 'sdk-go/**/*.go'
    - 'sdk-go/**/*.sh'
    - 'sdk-typescript/**/*.js'
    - 'sdk-typescript/**/*.ts'
    - 'sdk-typescript/**/*.tsx'
    - 'sdk-python/**/*.py'
    - 'sdk-ruby/**/*.rb'
    - 'sdk-java/**/*.java'

  paths-ignore:
    - '**/*api-client*/**'
    - 'hack/**'
    - '**/node_modules/**'
    - '**/dist/**'
    - '**/build/**'
    - '**/.venv/**'
    - '**/.gradle/**'

  comment: on-failure
