=begin
#Daytona Toolbox API

#Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module DaytonaToolboxApiClient
  class DaemonErrorCode
    CodeGitAuthFailed = "GIT_AUTH_FAILED".freeze
    CodeGitRepoNotFound = "GIT_REPO_NOT_FOUND".freeze
    CodeGitBranchNotFound = "GIT_BRANCH_NOT_FOUND".freeze
    CodeGitBranchExists = "GIT_BRANCH_EXISTS".freeze
    CodeGitPushRejected = "GIT_PUSH_REJECTED".freeze
    CodeGitDirtyWorktree = "GIT_DIRTY_WORKTREE".freeze
    CodeGitMergeConflict = "GIT_MERGE_CONFLICT".freeze
    CodeFileNotFound = "FILE_NOT_FOUND".freeze
    CodeFileAccessDenied = "FILE_ACCESS_DENIED".freeze
    CodeLspServerNotInitialized = "LSP_SERVER_NOT_INITIALIZED".freeze
    CodeProcessExecutionTimeout = "PROCESS_EXECUTION_TIMEOUT".freeze
    CodeProcessNotFound = "PROCESS_NOT_FOUND".freeze
    CodeSessionEnded = "SESSION_ENDED".freeze
    CodeCommandAlreadyCompleted = "COMMAND_ALREADY_COMPLETED".freeze
    CodeA11yUnavailable = "A11Y_UNAVAILABLE".freeze
    CodeRecordingStillActive = "RECORDING_STILL_ACTIVE".freeze
    CodeRecordingFfmpegNotFound = "RECORDING_FFMPEG_NOT_FOUND".freeze
    CodeBadRequest = "BAD_REQUEST".freeze
    CodeInvalidRequestBody = "INVALID_REQUEST_BODY".freeze
    CodeUnauthorized = "UNAUTHORIZED".freeze
    CodeForbidden = "FORBIDDEN".freeze
    CodeNotFound = "NOT_FOUND".freeze
    CodeConflict = "CONFLICT".freeze
    CodeRequestTimeout = "REQUEST_TIMEOUT".freeze
    CodeGone = "GONE".freeze
    CodeUnprocessableEntity = "UNPROCESSABLE_ENTITY".freeze
    CodeInternalServerError = "INTERNAL_SERVER_ERROR".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [CodeGitAuthFailed, CodeGitRepoNotFound, CodeGitBranchNotFound, CodeGitBranchExists, CodeGitPushRejected, CodeGitDirtyWorktree, CodeGitMergeConflict, CodeFileNotFound, CodeFileAccessDenied, CodeLspServerNotInitialized, CodeProcessExecutionTimeout, CodeProcessNotFound, CodeSessionEnded, CodeCommandAlreadyCompleted, CodeA11yUnavailable, CodeRecordingStillActive, CodeRecordingFfmpegNotFound, CodeBadRequest, CodeInvalidRequestBody, CodeUnauthorized, CodeForbidden, CodeNotFound, CodeConflict, CodeRequestTimeout, CodeGone, CodeUnprocessableEntity, CodeInternalServerError, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DaemonErrorCode.all_vars.include?(value)
      UNKNOWN_DEFAULT_OPEN_API
    end
  end
end
