# coding: utf-8

"""
    Daytona

    Daytona AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: support@daytona.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import TypeAdapter
from typing import Optional, Set
from typing_extensions import Self

_JSON_ADAPTER = TypeAdapter(Dict[str, Any])

class IntFilter(BaseModel):
    """
    IntFilter
    """ # noqa: E501
    eq: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values equal to this value.")
    var_not: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values not equal to this value.", serialization_alias="not")
    var_in: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Match values present in this list. Accepts comma-separated values or repeated query parameters. Maximum 100 entries.", serialization_alias="in")
    not_in: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Match values not present in this list. Accepts comma-separated values or repeated query parameters. Maximum 100 entries.", serialization_alias="notIn")
    gte: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values greater than or equal to this value.")
    lte: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values less than or equal to this value.")
    gt: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values strictly greater than this value.")
    lt: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Match values strictly less than this value.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["eq", "not", "in", "notIn", "gte", "lte", "gt", "lt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return _JSON_ADAPTER.dump_json(self.to_dict()).decode()

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eq": obj.get("eq"),
            "var_not": obj.get("not"),
            "var_in": obj.get("in"),
            "not_in": obj.get("notIn"),
            "gte": obj.get("gte"),
            "lte": obj.get("lte"),
            "gt": obj.get("gt"),
            "lt": obj.get("lt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


