# coding: utf-8

"""
    Daytona

    Daytona AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: support@daytona.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from daytona_api_client_async.models.volume_state import VolumeState
from daytona_api_client_async.models.webhook_event import WebhookEvent
from pydantic import TypeAdapter
from typing import Optional, Set
from typing_extensions import Self

_JSON_ADAPTER = TypeAdapter(Dict[str, Any])

class VolumeCreatedWebhook(BaseModel):
    """
    VolumeCreatedWebhook
    """ # noqa: E501
    event: WebhookEvent = Field(description="Event type identifier")
    timestamp: datetime = Field(description="Timestamp when the event occurred")
    id: StrictStr = Field(description="Volume ID")
    name: StrictStr = Field(description="Volume name")
    organization_id: StrictStr = Field(description="Organization ID", serialization_alias="organizationId")
    state: VolumeState = Field(description="Volume state")
    created_at: datetime = Field(description="When the volume was created", serialization_alias="createdAt")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["event", "timestamp", "id", "name", "organizationId", "state", "createdAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return _JSON_ADAPTER.dump_json(self.to_dict()).decode()

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VolumeCreatedWebhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VolumeCreatedWebhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event": obj.get("event"),
            "timestamp": obj.get("timestamp"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "organization_id": obj.get("organizationId"),
            "state": obj.get("state"),
            "created_at": obj.get("createdAt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


