/*
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ProcessTerminalReason
 */
@JsonAdapter(ProcessTerminalReason.Adapter.class)
public enum ProcessTerminalReason {
  
  ReasonExited("exited"),
  
  ReasonSignaled("signaled"),
  
  ReasonTimedOut("timed_out"),
  
  ReasonSandboxStopped("sandbox_stopped"),
  
  ReasonFailed("failed"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  ProcessTerminalReason(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProcessTerminalReason fromValue(String value) {
    for (ProcessTerminalReason b : ProcessTerminalReason.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<ProcessTerminalReason> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProcessTerminalReason enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProcessTerminalReason read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProcessTerminalReason.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ProcessTerminalReason.fromValue(value);
  }
}

