/*
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.daytona.toolbox.client.JSON;

/**
 * UpdateEnvRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class UpdateEnvRequest {
  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  @javax.annotation.Nullable
  private Map<String, String> set = new HashMap<>();

  public static final String SERIALIZED_NAME_UNSET = "unset";
  @SerializedName(SERIALIZED_NAME_UNSET)
  @javax.annotation.Nullable
  private List<String> unset = new ArrayList<>();

  public static final String SERIALIZED_NAME_UNSET_VALUE_PREFIX = "unsetValuePrefix";
  @SerializedName(SERIALIZED_NAME_UNSET_VALUE_PREFIX)
  @javax.annotation.Nullable
  private String unsetValuePrefix;

  public UpdateEnvRequest() {
  }

  public UpdateEnvRequest set(@javax.annotation.Nullable Map<String, String> set) {
    this.set = set;
    return this;
  }

  public UpdateEnvRequest putSetItem(String key, String setItem) {
    if (this.set == null) {
      this.set = new HashMap<>();
    }
    this.set.put(key, setItem);
    return this;
  }

  /**
   * Set maps env var names to values applied to the daemon&#39;s process env, so processes spawned after the call (exec, sessions, PTYs) inherit them.
   * @return set
   */
  @javax.annotation.Nullable
  public Map<String, String> getSet() {
    return set;
  }

  public void setSet(@javax.annotation.Nullable Map<String, String> set) {
    this.set = set;
  }


  public UpdateEnvRequest unset(@javax.annotation.Nullable List<String> unset) {
    this.unset = unset;
    return this;
  }

  public UpdateEnvRequest addUnsetItem(String unsetItem) {
    if (this.unset == null) {
      this.unset = new ArrayList<>();
    }
    this.unset.add(unsetItem);
    return this;
  }

  /**
   * Unset lists env var names to remove before Set is applied.
   * @return unset
   */
  @javax.annotation.Nullable
  public List<String> getUnset() {
    return unset;
  }

  public void setUnset(@javax.annotation.Nullable List<String> unset) {
    this.unset = unset;
  }


  public UpdateEnvRequest unsetValuePrefix(@javax.annotation.Nullable String unsetValuePrefix) {
    this.unsetValuePrefix = unsetValuePrefix;
    return this;
  }

  /**
   * UnsetValuePrefix removes every env var whose value has this prefix and whose name is not a key of Set, before Set is applied. Used to reconcile secret placeholder vars without the caller knowing the daemon&#39;s env.
   * @return unsetValuePrefix
   */
  @javax.annotation.Nullable
  public String getUnsetValuePrefix() {
    return unsetValuePrefix;
  }

  public void setUnsetValuePrefix(@javax.annotation.Nullable String unsetValuePrefix) {
    this.unsetValuePrefix = unsetValuePrefix;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateEnvRequest instance itself
   */
  public UpdateEnvRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateEnvRequest updateEnvRequest = (UpdateEnvRequest) o;
    return Objects.equals(this.set, updateEnvRequest.set) &&
        Objects.equals(this.unset, updateEnvRequest.unset) &&
        Objects.equals(this.unsetValuePrefix, updateEnvRequest.unsetValuePrefix)&&
        Objects.equals(this.additionalProperties, updateEnvRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(set, unset, unsetValuePrefix, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateEnvRequest {\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    unset: ").append(toIndentedString(unset)).append("\n");
    sb.append("    unsetValuePrefix: ").append(toIndentedString(unsetValuePrefix)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("set", "unset", "unsetValuePrefix"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateEnvRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateEnvRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateEnvRequest is not found in the empty JSON string", UpdateEnvRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("unset") != null && !jsonObj.get("unset").isJsonNull() && !jsonObj.get("unset").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `unset` to be an array in the JSON string but got `%s`", jsonObj.get("unset").toString()));
      }
      if ((jsonObj.get("unsetValuePrefix") != null && !jsonObj.get("unsetValuePrefix").isJsonNull()) && !jsonObj.get("unsetValuePrefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `unsetValuePrefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unsetValuePrefix").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateEnvRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateEnvRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateEnvRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateEnvRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateEnvRequest>() {
           @Override
           public void write(JsonWriter out, UpdateEnvRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateEnvRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateEnvRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateEnvRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateEnvRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateEnvRequest
   */
  public static UpdateEnvRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateEnvRequest.class);
  }

  /**
   * Convert an instance of UpdateEnvRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

