/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The sandbox class supported by the runner. Defaults to container when omitted or null.
 */
@JsonAdapter(CreateRunnerSandboxClass.Adapter.class)
public enum CreateRunnerSandboxClass {
  
  CONTAINER("container"),
  
  LINUX_VM("linux-vm"),
  
  WINDOWS("windows"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  CreateRunnerSandboxClass(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CreateRunnerSandboxClass fromValue(String value) {
    for (CreateRunnerSandboxClass b : CreateRunnerSandboxClass.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CreateRunnerSandboxClass> {
    @Override
    public void write(final JsonWriter jsonWriter, final CreateRunnerSandboxClass enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CreateRunnerSandboxClass read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CreateRunnerSandboxClass.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CreateRunnerSandboxClass.fromValue(value);
  }
}

