/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.daytona.api.client.model.GpuType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.daytona.api.client.JSON;

/**
 * GpuCapacity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class GpuCapacity {
  public static final String SERIALIZED_NAME_GPU_TYPE = "gpuType";
  @SerializedName(SERIALIZED_NAME_GPU_TYPE)
  @javax.annotation.Nonnull
  private GpuType gpuType;

  public static final String SERIALIZED_NAME_AVAILABLE_ON_DEMAND = "availableOnDemand";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_ON_DEMAND)
  @javax.annotation.Nonnull
  private Integer availableOnDemand;

  public static final String SERIALIZED_NAME_AVAILABLE_SPOT = "availableSpot";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_SPOT)
  @javax.annotation.Nonnull
  private Integer availableSpot;

  public GpuCapacity() {
  }

  public GpuCapacity gpuType(@javax.annotation.Nonnull GpuType gpuType) {
    this.gpuType = gpuType;
    return this;
  }

  /**
   * Get gpuType
   * @return gpuType
   */
  @javax.annotation.Nonnull
  public GpuType getGpuType() {
    return gpuType;
  }

  public void setGpuType(@javax.annotation.Nonnull GpuType gpuType) {
    this.gpuType = gpuType;
  }


  public GpuCapacity availableOnDemand(@javax.annotation.Nonnull Integer availableOnDemand) {
    this.availableOnDemand = availableOnDemand;
    return this;
  }

  /**
   * GPU units available for on-demand placement across schedulable runners, including capacity occupied by spot sandboxes that are immediately reclaimable.
   * minimum: 0
   * @return availableOnDemand
   */
  @javax.annotation.Nonnull
  public Integer getAvailableOnDemand() {
    return availableOnDemand;
  }

  public void setAvailableOnDemand(@javax.annotation.Nonnull Integer availableOnDemand) {
    this.availableOnDemand = availableOnDemand;
  }


  public GpuCapacity availableSpot(@javax.annotation.Nonnull Integer availableSpot) {
    this.availableSpot = availableSpot;
    return this;
  }

  /**
   * GPU units currently free for spot placement across schedulable runners.
   * minimum: 0
   * @return availableSpot
   */
  @javax.annotation.Nonnull
  public Integer getAvailableSpot() {
    return availableSpot;
  }

  public void setAvailableSpot(@javax.annotation.Nonnull Integer availableSpot) {
    this.availableSpot = availableSpot;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GpuCapacity instance itself
   */
  public GpuCapacity putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GpuCapacity gpuCapacity = (GpuCapacity) o;
    return Objects.equals(this.gpuType, gpuCapacity.gpuType) &&
        Objects.equals(this.availableOnDemand, gpuCapacity.availableOnDemand) &&
        Objects.equals(this.availableSpot, gpuCapacity.availableSpot)&&
        Objects.equals(this.additionalProperties, gpuCapacity.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gpuType, availableOnDemand, availableSpot, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GpuCapacity {\n");
    sb.append("    gpuType: ").append(toIndentedString(gpuType)).append("\n");
    sb.append("    availableOnDemand: ").append(toIndentedString(availableOnDemand)).append("\n");
    sb.append("    availableSpot: ").append(toIndentedString(availableSpot)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("gpuType", "availableOnDemand", "availableSpot"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("gpuType", "availableOnDemand", "availableSpot"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GpuCapacity
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GpuCapacity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GpuCapacity is not found in the empty JSON string", GpuCapacity.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GpuCapacity.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `gpuType`
      GpuType.validateJsonElement(jsonObj.get("gpuType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GpuCapacity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GpuCapacity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GpuCapacity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GpuCapacity.class));

       return (TypeAdapter<T>) new TypeAdapter<GpuCapacity>() {
           @Override
           public void write(JsonWriter out, GpuCapacity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GpuCapacity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GpuCapacity instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GpuCapacity given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GpuCapacity
   * @throws IOException if the JSON string is invalid with respect to GpuCapacity
   */
  public static GpuCapacity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GpuCapacity.class);
  }

  /**
   * Convert an instance of GpuCapacity to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

