/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.api;

import io.daytona.api.client.ApiException;
import java.math.BigDecimal;
import io.daytona.api.client.model.CreateSecret;
import io.daytona.api.client.model.ListSecretsResponse;
import io.daytona.api.client.model.Secret;
import io.daytona.api.client.model.UpdateSecret;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretApi
 */
@Disabled
public class SecretApiTest {

    private final SecretApi api = new SecretApi();

    /**
     * Create secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSecretTest() throws ApiException {
        CreateSecret createSecret = null;
        String xDaytonaOrganizationID = null;
        Secret response = api.createSecret(createSecret, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSecretTest() throws ApiException {
        String secretId = null;
        String xDaytonaOrganizationID = null;
        api.deleteSecret(secretId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSecretTest() throws ApiException {
        String secretId = null;
        String xDaytonaOrganizationID = null;
        Secret response = api.getSecret(secretId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List secrets
     *
     * This endpoint is deprecated and fails for organizations with more than 1500 secrets. Use &#x60;listSecretsPaginated&#x60; instead.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSecretsTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        List<Secret> response = api.listSecrets(xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List secrets with pagination
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSecretsPaginatedTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        String cursor = null;
        BigDecimal limit = null;
        String name = null;
        String sort = null;
        String order = null;
        ListSecretsResponse response = api.listSecretsPaginated(xDaytonaOrganizationID, cursor, limit, name, sort, order);
        // TODO: test validations
    }

    /**
     * Update secret
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSecretTest() throws ApiException {
        String secretId = null;
        UpdateSecret updateSecret = null;
        String xDaytonaOrganizationID = null;
        Secret response = api.updateSecret(secretId, updateSecret, xDaytonaOrganizationID);
        // TODO: test validations
    }

}
