/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.api;

import io.daytona.api.client.ApiException;
import io.daytona.api.client.model.CreateVolume;
import io.daytona.api.client.model.CreateVolumeMountToken;
import io.daytona.api.client.model.HotmountRegion;
import io.daytona.api.client.model.Region;
import io.daytona.api.client.model.VolumeDto;
import io.daytona.api.client.model.VolumeMountTokenDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VolumesApi
 */
@Disabled
public class VolumesApiTest {

    private final VolumesApi api = new VolumesApi();

    /**
     * Create a new volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVolumeTest() throws ApiException {
        CreateVolume createVolume = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.createVolume(createVolume, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Create a mount token for a hotmount volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVolumeMountTokenTest() throws ApiException {
        String volumeId = null;
        String xDaytonaOrganizationID = null;
        CreateVolumeMountToken createVolumeMountToken = null;
        VolumeMountTokenDto response = api.createVolumeMountToken(volumeId, xDaytonaOrganizationID, createVolumeMountToken);
        // TODO: test validations
    }

    /**
     * Delete volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVolumeTest() throws ApiException {
        String volumeId = null;
        String xDaytonaOrganizationID = null;
        api.deleteVolume(volumeId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeTest() throws ApiException {
        String volumeId = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.getVolume(volumeId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details by name
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeByNameTest() throws ApiException {
        String name = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.getVolumeByName(name, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List regions where blockmount volumes can be created
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBlockmountRegionsTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        List<Region> response = api.listBlockmountRegions(xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List available hotmount regions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listHotmountRegionsTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        List<HotmountRegion> response = api.listHotmountRegions(xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List all volumes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listVolumesTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        Boolean includeDeleted = null;
        List<VolumeDto> response = api.listVolumes(xDaytonaOrganizationID, includeDeleted);
        // TODO: test validations
    }

}
