/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// checks if the KillProcessRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KillProcessRequest{}

// KillProcessRequest struct for KillProcessRequest
type KillProcessRequest struct {
	// EscalateAfterMs escalates to EscalateTo if the process is still alive after the grace period. This is what makes kill() honest for TERM-trapping processes: the trap runs and is captured, and the process still dies.
	EscalateAfterMs *int32 `json:"escalateAfterMs,omitempty"`
	EscalateTo *string `json:"escalateTo,omitempty"`
	Signal *string `json:"signal,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KillProcessRequest KillProcessRequest

// NewKillProcessRequest instantiates a new KillProcessRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKillProcessRequest() *KillProcessRequest {
	this := KillProcessRequest{}
	return &this
}

// NewKillProcessRequestWithDefaults instantiates a new KillProcessRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKillProcessRequestWithDefaults() *KillProcessRequest {
	this := KillProcessRequest{}
	return &this
}

// GetEscalateAfterMs returns the EscalateAfterMs field value if set, zero value otherwise.
func (o *KillProcessRequest) GetEscalateAfterMs() int32 {
	if o == nil || IsNil(o.EscalateAfterMs) {
		var ret int32
		return ret
	}
	return *o.EscalateAfterMs
}

// GetEscalateAfterMsOk returns a tuple with the EscalateAfterMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KillProcessRequest) GetEscalateAfterMsOk() (*int32, bool) {
	if o == nil || IsNil(o.EscalateAfterMs) {
		return nil, false
	}
	return o.EscalateAfterMs, true
}

// HasEscalateAfterMs returns a boolean if a field has been set.
func (o *KillProcessRequest) HasEscalateAfterMs() bool {
	if o != nil && !IsNil(o.EscalateAfterMs) {
		return true
	}

	return false
}

// SetEscalateAfterMs gets a reference to the given int32 and assigns it to the EscalateAfterMs field.
func (o *KillProcessRequest) SetEscalateAfterMs(v int32) {
	o.EscalateAfterMs = &v
}

// GetEscalateTo returns the EscalateTo field value if set, zero value otherwise.
func (o *KillProcessRequest) GetEscalateTo() string {
	if o == nil || IsNil(o.EscalateTo) {
		var ret string
		return ret
	}
	return *o.EscalateTo
}

// GetEscalateToOk returns a tuple with the EscalateTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KillProcessRequest) GetEscalateToOk() (*string, bool) {
	if o == nil || IsNil(o.EscalateTo) {
		return nil, false
	}
	return o.EscalateTo, true
}

// HasEscalateTo returns a boolean if a field has been set.
func (o *KillProcessRequest) HasEscalateTo() bool {
	if o != nil && !IsNil(o.EscalateTo) {
		return true
	}

	return false
}

// SetEscalateTo gets a reference to the given string and assigns it to the EscalateTo field.
func (o *KillProcessRequest) SetEscalateTo(v string) {
	o.EscalateTo = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *KillProcessRequest) GetSignal() string {
	if o == nil || IsNil(o.Signal) {
		var ret string
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KillProcessRequest) GetSignalOk() (*string, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *KillProcessRequest) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given string and assigns it to the Signal field.
func (o *KillProcessRequest) SetSignal(v string) {
	o.Signal = &v
}

func (o KillProcessRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KillProcessRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EscalateAfterMs) {
		toSerialize["escalateAfterMs"] = o.EscalateAfterMs
	}
	if !IsNil(o.EscalateTo) {
		toSerialize["escalateTo"] = o.EscalateTo
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KillProcessRequest) UnmarshalJSON(data []byte) (err error) {
	varKillProcessRequest := _KillProcessRequest{}

	err = json.Unmarshal(data, &varKillProcessRequest)

	if err != nil {
		return err
	}

	*o = KillProcessRequest(varKillProcessRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "escalateAfterMs")
		delete(additionalProperties, "escalateTo")
		delete(additionalProperties, "signal")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKillProcessRequest struct {
	value *KillProcessRequest
	isSet bool
}

func (v NullableKillProcessRequest) Get() *KillProcessRequest {
	return v.value
}

func (v *NullableKillProcessRequest) Set(val *KillProcessRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKillProcessRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKillProcessRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKillProcessRequest(val *KillProcessRequest) *NullableKillProcessRequest {
	return &NullableKillProcessRequest{value: val, isSet: true}
}

func (v NullableKillProcessRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKillProcessRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


