/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// ProcessState the model 'ProcessState'
type ProcessState string

// List of ProcessState
const (
	PROCESSSTATE_StateRunning ProcessState = "running"
	PROCESSSTATE_StateTerminal ProcessState = "terminal"
	PROCESSSTATE_UNKNOWN_DEFAULT_OPEN_API ProcessState = "11184809"
)

// All allowed values of ProcessState enum
var AllowedProcessStateEnumValues = []ProcessState{
	"running",
	"terminal",
	"11184809",
}

func (v *ProcessState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProcessState(value)
	for _, existing := range AllowedProcessStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = PROCESSSTATE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewProcessStateFromValue returns a pointer to a valid ProcessState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProcessStateFromValue(v string) (*ProcessState, error) {
	ev := ProcessState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := PROCESSSTATE_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProcessState) IsValid() bool {
	for _, existing := range AllowedProcessStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProcessState value
func (v ProcessState) Ptr() *ProcessState {
	return &v
}

type NullableProcessState struct {
	value *ProcessState
	isSet bool
}

func (v NullableProcessState) Get() *ProcessState {
	return v.value
}

func (v *NullableProcessState) Set(val *ProcessState) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessState) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessState(val *ProcessState) *NullableProcessState {
	return &NullableProcessState{value: val, isSet: true}
}

func (v NullableProcessState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

