/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// SessionKernel the model 'SessionKernel'
type SessionKernel string

// List of SessionKernel
const (
	SESSIONKERNEL_SessionKernelShell SessionKernel = "shell"
	SESSIONKERNEL_SessionKernelPython SessionKernel = "python"
	SESSIONKERNEL_UNKNOWN_DEFAULT_OPEN_API SessionKernel = "11184809"
)

// All allowed values of SessionKernel enum
var AllowedSessionKernelEnumValues = []SessionKernel{
	"shell",
	"python",
	"11184809",
}

func (v *SessionKernel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SessionKernel(value)
	for _, existing := range AllowedSessionKernelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SESSIONKERNEL_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewSessionKernelFromValue returns a pointer to a valid SessionKernel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSessionKernelFromValue(v string) (*SessionKernel, error) {
	ev := SessionKernel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := SESSIONKERNEL_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SessionKernel) IsValid() bool {
	for _, existing := range AllowedSessionKernelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SessionKernel value
func (v SessionKernel) Ptr() *SessionKernel {
	return &v
}

type NullableSessionKernel struct {
	value *SessionKernel
	isSet bool
}

func (v NullableSessionKernel) Get() *SessionKernel {
	return v.value
}

func (v *NullableSessionKernel) Set(val *SessionKernel) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionKernel) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionKernel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionKernel(val *SessionKernel) *NullableSessionKernel {
	return &NullableSessionKernel{value: val, isSet: true}
}

func (v NullableSessionKernel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionKernel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

