/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// checks if the MouseUpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MouseUpRequest{}

// MouseUpRequest struct for MouseUpRequest
type MouseUpRequest struct {
	// left, right, middle
	Button *string `json:"button,omitempty"`
	X *int32 `json:"x,omitempty"`
	Y *int32 `json:"y,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MouseUpRequest MouseUpRequest

// NewMouseUpRequest instantiates a new MouseUpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMouseUpRequest() *MouseUpRequest {
	this := MouseUpRequest{}
	return &this
}

// NewMouseUpRequestWithDefaults instantiates a new MouseUpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMouseUpRequestWithDefaults() *MouseUpRequest {
	this := MouseUpRequest{}
	return &this
}

// GetButton returns the Button field value if set, zero value otherwise.
func (o *MouseUpRequest) GetButton() string {
	if o == nil || IsNil(o.Button) {
		var ret string
		return ret
	}
	return *o.Button
}

// GetButtonOk returns a tuple with the Button field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MouseUpRequest) GetButtonOk() (*string, bool) {
	if o == nil || IsNil(o.Button) {
		return nil, false
	}
	return o.Button, true
}

// HasButton returns a boolean if a field has been set.
func (o *MouseUpRequest) HasButton() bool {
	if o != nil && !IsNil(o.Button) {
		return true
	}

	return false
}

// SetButton gets a reference to the given string and assigns it to the Button field.
func (o *MouseUpRequest) SetButton(v string) {
	o.Button = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *MouseUpRequest) GetX() int32 {
	if o == nil || IsNil(o.X) {
		var ret int32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MouseUpRequest) GetXOk() (*int32, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *MouseUpRequest) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given int32 and assigns it to the X field.
func (o *MouseUpRequest) SetX(v int32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *MouseUpRequest) GetY() int32 {
	if o == nil || IsNil(o.Y) {
		var ret int32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MouseUpRequest) GetYOk() (*int32, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *MouseUpRequest) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given int32 and assigns it to the Y field.
func (o *MouseUpRequest) SetY(v int32) {
	o.Y = &v
}

func (o MouseUpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MouseUpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Button) {
		toSerialize["button"] = o.Button
	}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MouseUpRequest) UnmarshalJSON(data []byte) (err error) {
	varMouseUpRequest := _MouseUpRequest{}

	err = json.Unmarshal(data, &varMouseUpRequest)

	if err != nil {
		return err
	}

	*o = MouseUpRequest(varMouseUpRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "button")
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMouseUpRequest struct {
	value *MouseUpRequest
	isSet bool
}

func (v NullableMouseUpRequest) Get() *MouseUpRequest {
	return v.value
}

func (v *NullableMouseUpRequest) Set(val *MouseUpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMouseUpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMouseUpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMouseUpRequest(val *MouseUpRequest) *NullableMouseUpRequest {
	return &NullableMouseUpRequest{value: val, isSet: true}
}

func (v NullableMouseUpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMouseUpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


