/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
	"fmt"
)

// checks if the ProcessLogFrame type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessLogFrame{}

// ProcessLogFrame struct for ProcessLogFrame
type ProcessLogFrame struct {
	Channel ProcessLogChannel `json:"channel"`
	Cursor string `json:"cursor"`
	// Data is UTF-8 text when encoding=text, base64 when encoding=base64.
	Data *string `json:"data,omitempty"`
	Encoding *string `json:"encoding,omitempty"`
	Seq int32 `json:"seq"`
	Timestamp string `json:"timestamp"`
	AdditionalProperties map[string]interface{}
}

type _ProcessLogFrame ProcessLogFrame

// NewProcessLogFrame instantiates a new ProcessLogFrame object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessLogFrame(channel ProcessLogChannel, cursor string, seq int32, timestamp string) *ProcessLogFrame {
	this := ProcessLogFrame{}
	this.Channel = channel
	this.Cursor = cursor
	this.Seq = seq
	this.Timestamp = timestamp
	return &this
}

// NewProcessLogFrameWithDefaults instantiates a new ProcessLogFrame object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessLogFrameWithDefaults() *ProcessLogFrame {
	this := ProcessLogFrame{}
	return &this
}

// GetChannel returns the Channel field value
func (o *ProcessLogFrame) GetChannel() ProcessLogChannel {
	if o == nil {
		var ret ProcessLogChannel
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetChannelOk() (*ProcessLogChannel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *ProcessLogFrame) SetChannel(v ProcessLogChannel) {
	o.Channel = v
}

// GetCursor returns the Cursor field value
func (o *ProcessLogFrame) GetCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *ProcessLogFrame) SetCursor(v string) {
	o.Cursor = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ProcessLogFrame) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ProcessLogFrame) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *ProcessLogFrame) SetData(v string) {
	o.Data = &v
}

// GetEncoding returns the Encoding field value if set, zero value otherwise.
func (o *ProcessLogFrame) GetEncoding() string {
	if o == nil || IsNil(o.Encoding) {
		var ret string
		return ret
	}
	return *o.Encoding
}

// GetEncodingOk returns a tuple with the Encoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetEncodingOk() (*string, bool) {
	if o == nil || IsNil(o.Encoding) {
		return nil, false
	}
	return o.Encoding, true
}

// HasEncoding returns a boolean if a field has been set.
func (o *ProcessLogFrame) HasEncoding() bool {
	if o != nil && !IsNil(o.Encoding) {
		return true
	}

	return false
}

// SetEncoding gets a reference to the given string and assigns it to the Encoding field.
func (o *ProcessLogFrame) SetEncoding(v string) {
	o.Encoding = &v
}

// GetSeq returns the Seq field value
func (o *ProcessLogFrame) GetSeq() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetSeqOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *ProcessLogFrame) SetSeq(v int32) {
	o.Seq = v
}

// GetTimestamp returns the Timestamp field value
func (o *ProcessLogFrame) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ProcessLogFrame) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ProcessLogFrame) SetTimestamp(v string) {
	o.Timestamp = v
}

func (o ProcessLogFrame) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessLogFrame) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	toSerialize["cursor"] = o.Cursor
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Encoding) {
		toSerialize["encoding"] = o.Encoding
	}
	toSerialize["seq"] = o.Seq
	toSerialize["timestamp"] = o.Timestamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProcessLogFrame) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channel",
		"cursor",
		"seq",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessLogFrame := _ProcessLogFrame{}

	err = json.Unmarshal(data, &varProcessLogFrame)

	if err != nil {
		return err
	}

	*o = ProcessLogFrame(varProcessLogFrame)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channel")
		delete(additionalProperties, "cursor")
		delete(additionalProperties, "data")
		delete(additionalProperties, "encoding")
		delete(additionalProperties, "seq")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProcessLogFrame struct {
	value *ProcessLogFrame
	isSet bool
}

func (v NullableProcessLogFrame) Get() *ProcessLogFrame {
	return v.value
}

func (v *NullableProcessLogFrame) Set(val *ProcessLogFrame) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessLogFrame) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessLogFrame) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessLogFrame(val *ProcessLogFrame) *NullableProcessLogFrame {
	return &NullableProcessLogFrame{value: val, isSet: true}
}

func (v NullableProcessLogFrame) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessLogFrame) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


