/*
Daytona Toolbox API

Daytona Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// ProcessKeepLogs the model 'ProcessKeepLogs'
type ProcessKeepLogs string

// List of ProcessKeepLogs
const (
	PROCESSKEEPLOGS_KeepLogsUntilCleanup ProcessKeepLogs = "until_cleanup"
	PROCESSKEEPLOGS_KeepLogsOnExitTTL ProcessKeepLogs = "on_exit_ttl"
	PROCESSKEEPLOGS_KeepLogsNone ProcessKeepLogs = "none"
	PROCESSKEEPLOGS_UNKNOWN_DEFAULT_OPEN_API ProcessKeepLogs = "11184809"
)

// All allowed values of ProcessKeepLogs enum
var AllowedProcessKeepLogsEnumValues = []ProcessKeepLogs{
	"until_cleanup",
	"on_exit_ttl",
	"none",
	"11184809",
}

func (v *ProcessKeepLogs) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProcessKeepLogs(value)
	for _, existing := range AllowedProcessKeepLogsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = PROCESSKEEPLOGS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewProcessKeepLogsFromValue returns a pointer to a valid ProcessKeepLogs
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProcessKeepLogsFromValue(v string) (*ProcessKeepLogs, error) {
	ev := ProcessKeepLogs(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := PROCESSKEEPLOGS_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProcessKeepLogs) IsValid() bool {
	for _, existing := range AllowedProcessKeepLogsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProcessKeepLogs value
func (v ProcessKeepLogs) Ptr() *ProcessKeepLogs {
	return &v
}

type NullableProcessKeepLogs struct {
	value *ProcessKeepLogs
	isSet bool
}

func (v NullableProcessKeepLogs) Get() *ProcessKeepLogs {
	return v.value
}

func (v *NullableProcessKeepLogs) Set(val *ProcessKeepLogs) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessKeepLogs) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessKeepLogs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessKeepLogs(val *ProcessKeepLogs) *NullableProcessKeepLogs {
	return &NullableProcessKeepLogs{value: val, isSet: true}
}

func (v NullableProcessKeepLogs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessKeepLogs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

