/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AccountProvider {
    /**
     * WorkOS identity provider, e.g. GoogleOAuth or GitHubOAuth
     */
    'provider': string;
    /**
     * Human-readable provider name
     */
    'displayName': string;
    /**
     * Whether the authenticated user has an identity from this provider
     */
    'linked': boolean;
}

