/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRunnerSandboxClass } from './create-runner-sandbox-class';

export interface CreateRunner {
    'regionId': string;
    'name': string;
    /**
     * Tags to associate with the runner
     */
    'tags'?: Array<string>;
    /**
     * The sandbox class supported by the runner. Defaults to container when omitted or null.
     */
    'sandboxClass'?: CreateRunnerSandboxClass | null;
}



