/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkosAdminPortalIntent } from './workos-admin-portal-intent';

export interface GenerateWorkosAdminPortalLink {
    /**
     * Which setup flow to open: sso for a single sign-on connection, dsync for SCIM directory sync
     */
    'intent': WorkosAdminPortalIntent;
}



