/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface VolumeMountTokenDto {
    /**
     * The short-lived macaroon token the in-sandbox agent uses to mount the volume
     */
    'token': string;
    /**
     * The token expiration timestamp
     */
    'expiresAt': string;
    /**
     * The hotmount region the volume lives in
     */
    'region': string;
    /**
     * The gateway gRPC endpoint (SEAWEED_GATEWAY_GRPC)
     */
    'gatewayGrpc': string;
    /**
     * The gateway HTTPS endpoint (SEAWEED_GATEWAY_HTTP)
     */
    'gatewayHttp': string;
    /**
     * The binaries bucket base URL used to bootstrap the mount (SEAWEED_BINARIES_URL)
     */
    'binariesUrl': string;
    /**
     * The pinned client binary version to use (SEAWEED_VERSION), when the region pins one
     */
    'version'?: string | null;
}

