/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Toolbox API
 * Daytona Toolbox API. The base URL comes from the sandbox\'s `toolboxProxyUrl` field (returned in sandbox DTO by the main Daytona API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Daytona Cloud: `https://proxy.app.daytona.io/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const DaemonErrorCode = {
    CodeGitAuthFailed: 'GIT_AUTH_FAILED',
    CodeGitRepoNotFound: 'GIT_REPO_NOT_FOUND',
    CodeGitBranchNotFound: 'GIT_BRANCH_NOT_FOUND',
    CodeGitBranchExists: 'GIT_BRANCH_EXISTS',
    CodeGitPushRejected: 'GIT_PUSH_REJECTED',
    CodeGitDirtyWorktree: 'GIT_DIRTY_WORKTREE',
    CodeGitMergeConflict: 'GIT_MERGE_CONFLICT',
    CodeFileNotFound: 'FILE_NOT_FOUND',
    CodeFileAccessDenied: 'FILE_ACCESS_DENIED',
    CodeLspServerNotInitialized: 'LSP_SERVER_NOT_INITIALIZED',
    CodeProcessExecutionTimeout: 'PROCESS_EXECUTION_TIMEOUT',
    CodeProcessNotFound: 'PROCESS_NOT_FOUND',
    CodeSessionEnded: 'SESSION_ENDED',
    CodeCommandAlreadyCompleted: 'COMMAND_ALREADY_COMPLETED',
    CodeA11yUnavailable: 'A11Y_UNAVAILABLE',
    CodeRecordingStillActive: 'RECORDING_STILL_ACTIVE',
    CodeRecordingFfmpegNotFound: 'RECORDING_FFMPEG_NOT_FOUND',
    CodeBadRequest: 'BAD_REQUEST',
    CodeInvalidRequestBody: 'INVALID_REQUEST_BODY',
    CodeUnauthorized: 'UNAUTHORIZED',
    CodeForbidden: 'FORBIDDEN',
    CodeNotFound: 'NOT_FOUND',
    CodeConflict: 'CONFLICT',
    CodeRequestTimeout: 'REQUEST_TIMEOUT',
    CodeGone: 'GONE',
    CodeUnprocessableEntity: 'UNPROCESSABLE_ENTITY',
    CodeInternalServerError: 'INTERNAL_SERVER_ERROR',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type DaemonErrorCode = typeof DaemonErrorCode[keyof typeof DaemonErrorCode];



