/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type WarmPoolsAPI interface {

	/*
	CreateWarmPool Create a warm pool

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return WarmPoolsAPICreateWarmPoolRequest
	*/
	CreateWarmPool(ctx context.Context) WarmPoolsAPICreateWarmPoolRequest

	// CreateWarmPoolExecute executes the request
	//  @return WarmPool
	CreateWarmPoolExecute(r WarmPoolsAPICreateWarmPoolRequest) (*WarmPool, *http.Response, error)

	/*
	DeleteWarmPool Delete a warm pool

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Warm pool ID
	@return WarmPoolsAPIDeleteWarmPoolRequest
	*/
	DeleteWarmPool(ctx context.Context, id string) WarmPoolsAPIDeleteWarmPoolRequest

	// DeleteWarmPoolExecute executes the request
	DeleteWarmPoolExecute(r WarmPoolsAPIDeleteWarmPoolRequest) (*http.Response, error)

	/*
	ListWarmPools List warm pools for the organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return WarmPoolsAPIListWarmPoolsRequest
	*/
	ListWarmPools(ctx context.Context) WarmPoolsAPIListWarmPoolsRequest

	// ListWarmPoolsExecute executes the request
	//  @return []WarmPool
	ListWarmPoolsExecute(r WarmPoolsAPIListWarmPoolsRequest) ([]WarmPool, *http.Response, error)

	/*
	UpdateWarmPool Update a warm pool size

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Warm pool ID
	@return WarmPoolsAPIUpdateWarmPoolRequest
	*/
	UpdateWarmPool(ctx context.Context, id string) WarmPoolsAPIUpdateWarmPoolRequest

	// UpdateWarmPoolExecute executes the request
	//  @return WarmPool
	UpdateWarmPoolExecute(r WarmPoolsAPIUpdateWarmPoolRequest) (*WarmPool, *http.Response, error)
}

// WarmPoolsAPIService WarmPoolsAPI service
type WarmPoolsAPIService service

type WarmPoolsAPICreateWarmPoolRequest struct {
	ctx context.Context
	ApiService WarmPoolsAPI
	createWarmPool *CreateWarmPool
	xDaytonaOrganizationID *string
}

func (r WarmPoolsAPICreateWarmPoolRequest) CreateWarmPool(createWarmPool CreateWarmPool) WarmPoolsAPICreateWarmPoolRequest {
	r.createWarmPool = &createWarmPool
	return r
}

// Use with JWT to specify the organization ID
func (r WarmPoolsAPICreateWarmPoolRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) WarmPoolsAPICreateWarmPoolRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r WarmPoolsAPICreateWarmPoolRequest) Execute() (*WarmPool, *http.Response, error) {
	return r.ApiService.CreateWarmPoolExecute(r)
}

/*
CreateWarmPool Create a warm pool

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return WarmPoolsAPICreateWarmPoolRequest
*/
func (a *WarmPoolsAPIService) CreateWarmPool(ctx context.Context) WarmPoolsAPICreateWarmPoolRequest {
	return WarmPoolsAPICreateWarmPoolRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return WarmPool
func (a *WarmPoolsAPIService) CreateWarmPoolExecute(r WarmPoolsAPICreateWarmPoolRequest) (*WarmPool, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WarmPool
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WarmPoolsAPIService.CreateWarmPool")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/warm-pools"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createWarmPool == nil {
		return localVarReturnValue, nil, reportError("createWarmPool is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.createWarmPool
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type WarmPoolsAPIDeleteWarmPoolRequest struct {
	ctx context.Context
	ApiService WarmPoolsAPI
	id string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r WarmPoolsAPIDeleteWarmPoolRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) WarmPoolsAPIDeleteWarmPoolRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r WarmPoolsAPIDeleteWarmPoolRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteWarmPoolExecute(r)
}

/*
DeleteWarmPool Delete a warm pool

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Warm pool ID
 @return WarmPoolsAPIDeleteWarmPoolRequest
*/
func (a *WarmPoolsAPIService) DeleteWarmPool(ctx context.Context, id string) WarmPoolsAPIDeleteWarmPoolRequest {
	return WarmPoolsAPIDeleteWarmPoolRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *WarmPoolsAPIService) DeleteWarmPoolExecute(r WarmPoolsAPIDeleteWarmPoolRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WarmPoolsAPIService.DeleteWarmPool")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/warm-pools/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type WarmPoolsAPIListWarmPoolsRequest struct {
	ctx context.Context
	ApiService WarmPoolsAPI
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r WarmPoolsAPIListWarmPoolsRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) WarmPoolsAPIListWarmPoolsRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r WarmPoolsAPIListWarmPoolsRequest) Execute() ([]WarmPool, *http.Response, error) {
	return r.ApiService.ListWarmPoolsExecute(r)
}

/*
ListWarmPools List warm pools for the organization

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return WarmPoolsAPIListWarmPoolsRequest
*/
func (a *WarmPoolsAPIService) ListWarmPools(ctx context.Context) WarmPoolsAPIListWarmPoolsRequest {
	return WarmPoolsAPIListWarmPoolsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []WarmPool
func (a *WarmPoolsAPIService) ListWarmPoolsExecute(r WarmPoolsAPIListWarmPoolsRequest) ([]WarmPool, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []WarmPool
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WarmPoolsAPIService.ListWarmPools")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/warm-pools"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type WarmPoolsAPIUpdateWarmPoolRequest struct {
	ctx context.Context
	ApiService WarmPoolsAPI
	id string
	updateWarmPool *UpdateWarmPool
	xDaytonaOrganizationID *string
}

func (r WarmPoolsAPIUpdateWarmPoolRequest) UpdateWarmPool(updateWarmPool UpdateWarmPool) WarmPoolsAPIUpdateWarmPoolRequest {
	r.updateWarmPool = &updateWarmPool
	return r
}

// Use with JWT to specify the organization ID
func (r WarmPoolsAPIUpdateWarmPoolRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) WarmPoolsAPIUpdateWarmPoolRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r WarmPoolsAPIUpdateWarmPoolRequest) Execute() (*WarmPool, *http.Response, error) {
	return r.ApiService.UpdateWarmPoolExecute(r)
}

/*
UpdateWarmPool Update a warm pool size

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id Warm pool ID
 @return WarmPoolsAPIUpdateWarmPoolRequest
*/
func (a *WarmPoolsAPIService) UpdateWarmPool(ctx context.Context, id string) WarmPoolsAPIUpdateWarmPoolRequest {
	return WarmPoolsAPIUpdateWarmPoolRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return WarmPool
func (a *WarmPoolsAPIService) UpdateWarmPoolExecute(r WarmPoolsAPIUpdateWarmPoolRequest) (*WarmPool, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WarmPool
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WarmPoolsAPIService.UpdateWarmPool")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/warm-pools/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateWarmPool == nil {
		return localVarReturnValue, nil, reportError("updateWarmPool is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.updateWarmPool
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
