/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the UpdateLastActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLastActivity{}

// UpdateLastActivity struct for UpdateLastActivity
type UpdateLastActivity struct {
	// Optional type of interaction that reset the activity timer.
	ActivityType *string `json:"activityType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateLastActivity UpdateLastActivity

// NewUpdateLastActivity instantiates a new UpdateLastActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLastActivity() *UpdateLastActivity {
	this := UpdateLastActivity{}
	return &this
}

// NewUpdateLastActivityWithDefaults instantiates a new UpdateLastActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLastActivityWithDefaults() *UpdateLastActivity {
	this := UpdateLastActivity{}
	return &this
}

// GetActivityType returns the ActivityType field value if set, zero value otherwise.
func (o *UpdateLastActivity) GetActivityType() string {
	if o == nil || IsNil(o.ActivityType) {
		var ret string
		return ret
	}
	return *o.ActivityType
}

// GetActivityTypeOk returns a tuple with the ActivityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLastActivity) GetActivityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ActivityType) {
		return nil, false
	}
	return o.ActivityType, true
}

// HasActivityType returns a boolean if a field has been set.
func (o *UpdateLastActivity) HasActivityType() bool {
	if o != nil && !IsNil(o.ActivityType) {
		return true
	}

	return false
}

// SetActivityType gets a reference to the given string and assigns it to the ActivityType field.
func (o *UpdateLastActivity) SetActivityType(v string) {
	o.ActivityType = &v
}

func (o UpdateLastActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLastActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActivityType) {
		toSerialize["activityType"] = o.ActivityType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateLastActivity) UnmarshalJSON(data []byte) (err error) {
	varUpdateLastActivity := _UpdateLastActivity{}

	err = json.Unmarshal(data, &varUpdateLastActivity)

	if err != nil {
		return err
	}

	*o = UpdateLastActivity(varUpdateLastActivity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "activityType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateLastActivity struct {
	value *UpdateLastActivity
	isSet bool
}

func (v NullableUpdateLastActivity) Get() *UpdateLastActivity {
	return v.value
}

func (v *NullableUpdateLastActivity) Set(val *UpdateLastActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLastActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLastActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLastActivity(val *UpdateLastActivity) *NullableUpdateLastActivity {
	return &NullableUpdateLastActivity{value: val, isSet: true}
}

func (v NullableUpdateLastActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLastActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


