/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SandboxIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxIdentity{}

// SandboxIdentity struct for SandboxIdentity
type SandboxIdentity struct {
	// Sandbox ID
	SandboxId string `json:"sandboxId"`
	// Organization ID
	OrganizationId string `json:"organizationId"`
	AdditionalProperties map[string]interface{}
}

type _SandboxIdentity SandboxIdentity

// NewSandboxIdentity instantiates a new SandboxIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxIdentity(sandboxId string, organizationId string) *SandboxIdentity {
	this := SandboxIdentity{}
	this.SandboxId = sandboxId
	this.OrganizationId = organizationId
	return &this
}

// NewSandboxIdentityWithDefaults instantiates a new SandboxIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxIdentityWithDefaults() *SandboxIdentity {
	this := SandboxIdentity{}
	return &this
}

// GetSandboxId returns the SandboxId field value
func (o *SandboxIdentity) GetSandboxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SandboxId
}

// GetSandboxIdOk returns a tuple with the SandboxId field value
// and a boolean to check if the value has been set.
func (o *SandboxIdentity) GetSandboxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxId, true
}

// SetSandboxId sets field value
func (o *SandboxIdentity) SetSandboxId(v string) {
	o.SandboxId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *SandboxIdentity) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *SandboxIdentity) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *SandboxIdentity) SetOrganizationId(v string) {
	o.OrganizationId = v
}

func (o SandboxIdentity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sandboxId"] = o.SandboxId
	toSerialize["organizationId"] = o.OrganizationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SandboxIdentity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sandboxId",
		"organizationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSandboxIdentity := _SandboxIdentity{}

	err = json.Unmarshal(data, &varSandboxIdentity)

	if err != nil {
		return err
	}

	*o = SandboxIdentity(varSandboxIdentity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sandboxId")
		delete(additionalProperties, "organizationId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSandboxIdentity struct {
	value *SandboxIdentity
	isSet bool
}

func (v NullableSandboxIdentity) Get() *SandboxIdentity {
	return v.value
}

func (v *NullableSandboxIdentity) Set(val *SandboxIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxIdentity(val *SandboxIdentity) *NullableSandboxIdentity {
	return &NullableSandboxIdentity{value: val, isSet: true}
}

func (v NullableSandboxIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


