/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the WarmPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarmPool{}

// WarmPool struct for WarmPool
type WarmPool struct {
	Id string `json:"id"`
	OrganizationId string `json:"organizationId"`
	Snapshot string `json:"snapshot"`
	Target string `json:"target"`
	// Desired number of warm sandboxes
	Pool float32 `json:"pool"`
	// Current number of ready warm sandboxes in the pool
	CurrentSize float32 `json:"currentSize"`
	Cpu float32 `json:"cpu"`
	Mem float32 `json:"mem"`
	Disk float32 `json:"disk"`
	OsUser string `json:"osUser"`
	Env map[string]string `json:"env"`
	ErrorReason NullableString `json:"errorReason,omitempty"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _WarmPool WarmPool

// NewWarmPool instantiates a new WarmPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarmPool(id string, organizationId string, snapshot string, target string, pool float32, currentSize float32, cpu float32, mem float32, disk float32, osUser string, env map[string]string, createdAt string, updatedAt string) *WarmPool {
	this := WarmPool{}
	this.Id = id
	this.OrganizationId = organizationId
	this.Snapshot = snapshot
	this.Target = target
	this.Pool = pool
	this.CurrentSize = currentSize
	this.Cpu = cpu
	this.Mem = mem
	this.Disk = disk
	this.OsUser = osUser
	this.Env = env
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewWarmPoolWithDefaults instantiates a new WarmPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarmPoolWithDefaults() *WarmPool {
	this := WarmPool{}
	return &this
}

// GetId returns the Id field value
func (o *WarmPool) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WarmPool) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *WarmPool) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *WarmPool) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetSnapshot returns the Snapshot field value
func (o *WarmPool) GetSnapshot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetSnapshotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snapshot, true
}

// SetSnapshot sets field value
func (o *WarmPool) SetSnapshot(v string) {
	o.Snapshot = v
}

// GetTarget returns the Target field value
func (o *WarmPool) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *WarmPool) SetTarget(v string) {
	o.Target = v
}

// GetPool returns the Pool field value
func (o *WarmPool) GetPool() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Pool
}

// GetPoolOk returns a tuple with the Pool field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetPoolOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pool, true
}

// SetPool sets field value
func (o *WarmPool) SetPool(v float32) {
	o.Pool = v
}

// GetCurrentSize returns the CurrentSize field value
func (o *WarmPool) GetCurrentSize() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentSize
}

// GetCurrentSizeOk returns a tuple with the CurrentSize field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetCurrentSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentSize, true
}

// SetCurrentSize sets field value
func (o *WarmPool) SetCurrentSize(v float32) {
	o.CurrentSize = v
}

// GetCpu returns the Cpu field value
func (o *WarmPool) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *WarmPool) SetCpu(v float32) {
	o.Cpu = v
}

// GetMem returns the Mem field value
func (o *WarmPool) GetMem() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Mem
}

// GetMemOk returns a tuple with the Mem field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetMemOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mem, true
}

// SetMem sets field value
func (o *WarmPool) SetMem(v float32) {
	o.Mem = v
}

// GetDisk returns the Disk field value
func (o *WarmPool) GetDisk() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Disk
}

// GetDiskOk returns a tuple with the Disk field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetDiskOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disk, true
}

// SetDisk sets field value
func (o *WarmPool) SetDisk(v float32) {
	o.Disk = v
}

// GetOsUser returns the OsUser field value
func (o *WarmPool) GetOsUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OsUser
}

// GetOsUserOk returns a tuple with the OsUser field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetOsUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OsUser, true
}

// SetOsUser sets field value
func (o *WarmPool) SetOsUser(v string) {
	o.OsUser = v
}

// GetEnv returns the Env field value
func (o *WarmPool) GetEnv() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetEnvOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *WarmPool) SetEnv(v map[string]string) {
	o.Env = v
}

// GetErrorReason returns the ErrorReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WarmPool) GetErrorReason() string {
	if o == nil || IsNil(o.ErrorReason.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorReason.Get()
}

// GetErrorReasonOk returns a tuple with the ErrorReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WarmPool) GetErrorReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorReason.Get(), o.ErrorReason.IsSet()
}

// HasErrorReason returns a boolean if a field has been set.
func (o *WarmPool) HasErrorReason() bool {
	if o != nil && o.ErrorReason.IsSet() {
		return true
	}

	return false
}

// SetErrorReason gets a reference to the given NullableString and assigns it to the ErrorReason field.
func (o *WarmPool) SetErrorReason(v string) {
	o.ErrorReason.Set(&v)
}
// SetErrorReasonNil sets the value for ErrorReason to be an explicit nil
func (o *WarmPool) SetErrorReasonNil() {
	o.ErrorReason.Set(nil)
}

// UnsetErrorReason ensures that no value is present for ErrorReason, not even an explicit nil
func (o *WarmPool) UnsetErrorReason() {
	o.ErrorReason.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *WarmPool) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WarmPool) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WarmPool) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WarmPool) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WarmPool) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o WarmPool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarmPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["snapshot"] = o.Snapshot
	toSerialize["target"] = o.Target
	toSerialize["pool"] = o.Pool
	toSerialize["currentSize"] = o.CurrentSize
	toSerialize["cpu"] = o.Cpu
	toSerialize["mem"] = o.Mem
	toSerialize["disk"] = o.Disk
	toSerialize["osUser"] = o.OsUser
	toSerialize["env"] = o.Env
	if o.ErrorReason.IsSet() {
		toSerialize["errorReason"] = o.ErrorReason.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WarmPool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organizationId",
		"snapshot",
		"target",
		"pool",
		"currentSize",
		"cpu",
		"mem",
		"disk",
		"osUser",
		"env",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarmPool := _WarmPool{}

	err = json.Unmarshal(data, &varWarmPool)

	if err != nil {
		return err
	}

	*o = WarmPool(varWarmPool)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "snapshot")
		delete(additionalProperties, "target")
		delete(additionalProperties, "pool")
		delete(additionalProperties, "currentSize")
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "mem")
		delete(additionalProperties, "disk")
		delete(additionalProperties, "osUser")
		delete(additionalProperties, "env")
		delete(additionalProperties, "errorReason")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWarmPool struct {
	value *WarmPool
	isSet bool
}

func (v NullableWarmPool) Get() *WarmPool {
	return v.value
}

func (v *NullableWarmPool) Set(val *WarmPool) {
	v.value = val
	v.isSet = true
}

func (v NullableWarmPool) IsSet() bool {
	return v.isSet
}

func (v *NullableWarmPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarmPool(val *WarmPool) *NullableWarmPool {
	return &NullableWarmPool{value: val, isSet: true}
}

func (v NullableWarmPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarmPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


