/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PendingSsoLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PendingSsoLink{}

// PendingSsoLink struct for PendingSsoLink
type PendingSsoLink struct {
	Id string `json:"id"`
	// Display name of the identity provider requesting to be linked
	IdpName string `json:"idpName"`
	// Organization that configured the identity provider
	OrganizationId string `json:"organizationId"`
	// Email asserted by the identity provider
	ProviderEmail NullableString `json:"providerEmail"`
	CreatedAt string `json:"createdAt"`
	ExpiresAt string `json:"expiresAt"`
	AdditionalProperties map[string]interface{}
}

type _PendingSsoLink PendingSsoLink

// NewPendingSsoLink instantiates a new PendingSsoLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingSsoLink(id string, idpName string, organizationId string, providerEmail NullableString, createdAt string, expiresAt string) *PendingSsoLink {
	this := PendingSsoLink{}
	this.Id = id
	this.IdpName = idpName
	this.OrganizationId = organizationId
	this.ProviderEmail = providerEmail
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewPendingSsoLinkWithDefaults instantiates a new PendingSsoLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingSsoLinkWithDefaults() *PendingSsoLink {
	this := PendingSsoLink{}
	return &this
}

// GetId returns the Id field value
func (o *PendingSsoLink) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PendingSsoLink) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PendingSsoLink) SetId(v string) {
	o.Id = v
}

// GetIdpName returns the IdpName field value
func (o *PendingSsoLink) GetIdpName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdpName
}

// GetIdpNameOk returns a tuple with the IdpName field value
// and a boolean to check if the value has been set.
func (o *PendingSsoLink) GetIdpNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdpName, true
}

// SetIdpName sets field value
func (o *PendingSsoLink) SetIdpName(v string) {
	o.IdpName = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *PendingSsoLink) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *PendingSsoLink) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *PendingSsoLink) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetProviderEmail returns the ProviderEmail field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PendingSsoLink) GetProviderEmail() string {
	if o == nil || o.ProviderEmail.Get() == nil {
		var ret string
		return ret
	}

	return *o.ProviderEmail.Get()
}

// GetProviderEmailOk returns a tuple with the ProviderEmail field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PendingSsoLink) GetProviderEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderEmail.Get(), o.ProviderEmail.IsSet()
}

// SetProviderEmail sets field value
func (o *PendingSsoLink) SetProviderEmail(v string) {
	o.ProviderEmail.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *PendingSsoLink) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PendingSsoLink) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PendingSsoLink) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *PendingSsoLink) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *PendingSsoLink) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *PendingSsoLink) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

func (o PendingSsoLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PendingSsoLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["idpName"] = o.IdpName
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["providerEmail"] = o.ProviderEmail.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["expiresAt"] = o.ExpiresAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PendingSsoLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"idpName",
		"organizationId",
		"providerEmail",
		"createdAt",
		"expiresAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPendingSsoLink := _PendingSsoLink{}

	err = json.Unmarshal(data, &varPendingSsoLink)

	if err != nil {
		return err
	}

	*o = PendingSsoLink(varPendingSsoLink)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "idpName")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "providerEmail")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "expiresAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePendingSsoLink struct {
	value *PendingSsoLink
	isSet bool
}

func (v NullablePendingSsoLink) Get() *PendingSsoLink {
	return v.value
}

func (v *NullablePendingSsoLink) Set(val *PendingSsoLink) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingSsoLink) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingSsoLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingSsoLink(val *PendingSsoLink) *NullablePendingSsoLink {
	return &NullablePendingSsoLink{value: val, isSet: true}
}

func (v NullablePendingSsoLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingSsoLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


