/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the GpuCapacity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GpuCapacity{}

// GpuCapacity struct for GpuCapacity
type GpuCapacity struct {
	GpuType GpuType `json:"gpuType"`
	// GPU units available for on-demand placement across schedulable runners, including capacity occupied by spot sandboxes that are immediately reclaimable.
	AvailableOnDemand int32 `json:"availableOnDemand"`
	// GPU units currently free for spot placement across schedulable runners.
	AvailableSpot int32 `json:"availableSpot"`
	AdditionalProperties map[string]interface{}
}

type _GpuCapacity GpuCapacity

// NewGpuCapacity instantiates a new GpuCapacity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGpuCapacity(gpuType GpuType, availableOnDemand int32, availableSpot int32) *GpuCapacity {
	this := GpuCapacity{}
	this.GpuType = gpuType
	this.AvailableOnDemand = availableOnDemand
	this.AvailableSpot = availableSpot
	return &this
}

// NewGpuCapacityWithDefaults instantiates a new GpuCapacity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGpuCapacityWithDefaults() *GpuCapacity {
	this := GpuCapacity{}
	return &this
}

// GetGpuType returns the GpuType field value
func (o *GpuCapacity) GetGpuType() GpuType {
	if o == nil {
		var ret GpuType
		return ret
	}

	return o.GpuType
}

// GetGpuTypeOk returns a tuple with the GpuType field value
// and a boolean to check if the value has been set.
func (o *GpuCapacity) GetGpuTypeOk() (*GpuType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GpuType, true
}

// SetGpuType sets field value
func (o *GpuCapacity) SetGpuType(v GpuType) {
	o.GpuType = v
}

// GetAvailableOnDemand returns the AvailableOnDemand field value
func (o *GpuCapacity) GetAvailableOnDemand() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AvailableOnDemand
}

// GetAvailableOnDemandOk returns a tuple with the AvailableOnDemand field value
// and a boolean to check if the value has been set.
func (o *GpuCapacity) GetAvailableOnDemandOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableOnDemand, true
}

// SetAvailableOnDemand sets field value
func (o *GpuCapacity) SetAvailableOnDemand(v int32) {
	o.AvailableOnDemand = v
}

// GetAvailableSpot returns the AvailableSpot field value
func (o *GpuCapacity) GetAvailableSpot() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AvailableSpot
}

// GetAvailableSpotOk returns a tuple with the AvailableSpot field value
// and a boolean to check if the value has been set.
func (o *GpuCapacity) GetAvailableSpotOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableSpot, true
}

// SetAvailableSpot sets field value
func (o *GpuCapacity) SetAvailableSpot(v int32) {
	o.AvailableSpot = v
}

func (o GpuCapacity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GpuCapacity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gpuType"] = o.GpuType
	toSerialize["availableOnDemand"] = o.AvailableOnDemand
	toSerialize["availableSpot"] = o.AvailableSpot

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GpuCapacity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gpuType",
		"availableOnDemand",
		"availableSpot",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGpuCapacity := _GpuCapacity{}

	err = json.Unmarshal(data, &varGpuCapacity)

	if err != nil {
		return err
	}

	*o = GpuCapacity(varGpuCapacity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "gpuType")
		delete(additionalProperties, "availableOnDemand")
		delete(additionalProperties, "availableSpot")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGpuCapacity struct {
	value *GpuCapacity
	isSet bool
}

func (v NullableGpuCapacity) Get() *GpuCapacity {
	return v.value
}

func (v *NullableGpuCapacity) Set(val *GpuCapacity) {
	v.value = val
	v.isSet = true
}

func (v NullableGpuCapacity) IsSet() bool {
	return v.isSet
}

func (v *NullableGpuCapacity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGpuCapacity(val *GpuCapacity) *NullableGpuCapacity {
	return &NullableGpuCapacity{value: val, isSet: true}
}

func (v NullableGpuCapacity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGpuCapacity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


