/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SandboxStateUpdatedWebhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxStateUpdatedWebhook{}

// SandboxStateUpdatedWebhook struct for SandboxStateUpdatedWebhook
type SandboxStateUpdatedWebhook struct {
	// Event type identifier
	Event WebhookEvent `json:"event"`
	// Timestamp when the event occurred
	Timestamp time.Time `json:"timestamp"`
	// Sandbox ID
	Id string `json:"id"`
	// Organization ID
	OrganizationId string `json:"organizationId"`
	// Previous state
	OldState SandboxState `json:"oldState"`
	// New state
	NewState SandboxState `json:"newState"`
	// When the sandbox was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _SandboxStateUpdatedWebhook SandboxStateUpdatedWebhook

// NewSandboxStateUpdatedWebhook instantiates a new SandboxStateUpdatedWebhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxStateUpdatedWebhook(event WebhookEvent, timestamp time.Time, id string, organizationId string, oldState SandboxState, newState SandboxState, updatedAt time.Time) *SandboxStateUpdatedWebhook {
	this := SandboxStateUpdatedWebhook{}
	this.Event = event
	this.Timestamp = timestamp
	this.Id = id
	this.OrganizationId = organizationId
	this.OldState = oldState
	this.NewState = newState
	this.UpdatedAt = updatedAt
	return &this
}

// NewSandboxStateUpdatedWebhookWithDefaults instantiates a new SandboxStateUpdatedWebhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxStateUpdatedWebhookWithDefaults() *SandboxStateUpdatedWebhook {
	this := SandboxStateUpdatedWebhook{}
	return &this
}

// GetEvent returns the Event field value
func (o *SandboxStateUpdatedWebhook) GetEvent() WebhookEvent {
	if o == nil {
		var ret WebhookEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetEventOk() (*WebhookEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *SandboxStateUpdatedWebhook) SetEvent(v WebhookEvent) {
	o.Event = v
}

// GetTimestamp returns the Timestamp field value
func (o *SandboxStateUpdatedWebhook) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *SandboxStateUpdatedWebhook) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetId returns the Id field value
func (o *SandboxStateUpdatedWebhook) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SandboxStateUpdatedWebhook) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *SandboxStateUpdatedWebhook) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *SandboxStateUpdatedWebhook) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetOldState returns the OldState field value
func (o *SandboxStateUpdatedWebhook) GetOldState() SandboxState {
	if o == nil {
		var ret SandboxState
		return ret
	}

	return o.OldState
}

// GetOldStateOk returns a tuple with the OldState field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetOldStateOk() (*SandboxState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldState, true
}

// SetOldState sets field value
func (o *SandboxStateUpdatedWebhook) SetOldState(v SandboxState) {
	o.OldState = v
}

// GetNewState returns the NewState field value
func (o *SandboxStateUpdatedWebhook) GetNewState() SandboxState {
	if o == nil {
		var ret SandboxState
		return ret
	}

	return o.NewState
}

// GetNewStateOk returns a tuple with the NewState field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetNewStateOk() (*SandboxState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewState, true
}

// SetNewState sets field value
func (o *SandboxStateUpdatedWebhook) SetNewState(v SandboxState) {
	o.NewState = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SandboxStateUpdatedWebhook) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SandboxStateUpdatedWebhook) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SandboxStateUpdatedWebhook) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SandboxStateUpdatedWebhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxStateUpdatedWebhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["id"] = o.Id
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["oldState"] = o.OldState
	toSerialize["newState"] = o.NewState
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SandboxStateUpdatedWebhook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"timestamp",
		"id",
		"organizationId",
		"oldState",
		"newState",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSandboxStateUpdatedWebhook := _SandboxStateUpdatedWebhook{}

	err = json.Unmarshal(data, &varSandboxStateUpdatedWebhook)

	if err != nil {
		return err
	}

	*o = SandboxStateUpdatedWebhook(varSandboxStateUpdatedWebhook)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "id")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "oldState")
		delete(additionalProperties, "newState")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSandboxStateUpdatedWebhook struct {
	value *SandboxStateUpdatedWebhook
	isSet bool
}

func (v NullableSandboxStateUpdatedWebhook) Get() *SandboxStateUpdatedWebhook {
	return v.value
}

func (v *NullableSandboxStateUpdatedWebhook) Set(val *SandboxStateUpdatedWebhook) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxStateUpdatedWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxStateUpdatedWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxStateUpdatedWebhook(val *SandboxStateUpdatedWebhook) *NullableSandboxStateUpdatedWebhook {
	return &NullableSandboxStateUpdatedWebhook{value: val, isSet: true}
}

func (v NullableSandboxStateUpdatedWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxStateUpdatedWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


