/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the TestIdentityProviderConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestIdentityProviderConnection{}

// TestIdentityProviderConnection struct for TestIdentityProviderConnection
type TestIdentityProviderConnection struct {
	// OIDC Issuer URL to test
	IssuerUrl string `json:"issuerUrl"`
	AdditionalProperties map[string]interface{}
}

type _TestIdentityProviderConnection TestIdentityProviderConnection

// NewTestIdentityProviderConnection instantiates a new TestIdentityProviderConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestIdentityProviderConnection(issuerUrl string) *TestIdentityProviderConnection {
	this := TestIdentityProviderConnection{}
	this.IssuerUrl = issuerUrl
	return &this
}

// NewTestIdentityProviderConnectionWithDefaults instantiates a new TestIdentityProviderConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestIdentityProviderConnectionWithDefaults() *TestIdentityProviderConnection {
	this := TestIdentityProviderConnection{}
	return &this
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *TestIdentityProviderConnection) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *TestIdentityProviderConnection) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *TestIdentityProviderConnection) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

func (o TestIdentityProviderConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestIdentityProviderConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuerUrl"] = o.IssuerUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TestIdentityProviderConnection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"issuerUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTestIdentityProviderConnection := _TestIdentityProviderConnection{}

	err = json.Unmarshal(data, &varTestIdentityProviderConnection)

	if err != nil {
		return err
	}

	*o = TestIdentityProviderConnection(varTestIdentityProviderConnection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "issuerUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTestIdentityProviderConnection struct {
	value *TestIdentityProviderConnection
	isSet bool
}

func (v NullableTestIdentityProviderConnection) Get() *TestIdentityProviderConnection {
	return v.value
}

func (v *NullableTestIdentityProviderConnection) Set(val *TestIdentityProviderConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableTestIdentityProviderConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableTestIdentityProviderConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestIdentityProviderConnection(val *TestIdentityProviderConnection) *NullableTestIdentityProviderConnection {
	return &NullableTestIdentityProviderConnection{value: val, isSet: true}
}

func (v NullableTestIdentityProviderConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestIdentityProviderConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


