/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateRunner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRunner{}

// CreateRunner struct for CreateRunner
type CreateRunner struct {
	RegionId string `json:"regionId"`
	Name string `json:"name"`
	// Tags to associate with the runner
	Tags []string `json:"tags,omitempty"`
	// The sandbox class supported by the runner. Defaults to container when omitted or null.
	SandboxClass NullableCreateRunnerSandboxClass `json:"sandboxClass,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateRunner CreateRunner

// NewCreateRunner instantiates a new CreateRunner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRunner(regionId string, name string) *CreateRunner {
	this := CreateRunner{}
	this.RegionId = regionId
	this.Name = name
	var sandboxClass CreateRunnerSandboxClass = CREATERUNNERSANDBOXCLASS_CONTAINER
	this.SandboxClass = *NewNullableCreateRunnerSandboxClass(&sandboxClass)
	return &this
}

// NewCreateRunnerWithDefaults instantiates a new CreateRunner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRunnerWithDefaults() *CreateRunner {
	this := CreateRunner{}
	var sandboxClass CreateRunnerSandboxClass = CREATERUNNERSANDBOXCLASS_CONTAINER
	this.SandboxClass = *NewNullableCreateRunnerSandboxClass(&sandboxClass)
	return &this
}

// GetRegionId returns the RegionId field value
func (o *CreateRunner) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *CreateRunner) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *CreateRunner) SetRegionId(v string) {
	o.RegionId = v
}

// GetName returns the Name field value
func (o *CreateRunner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRunner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRunner) SetName(v string) {
	o.Name = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateRunner) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRunner) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateRunner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateRunner) SetTags(v []string) {
	o.Tags = v
}

// GetSandboxClass returns the SandboxClass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateRunner) GetSandboxClass() CreateRunnerSandboxClass {
	if o == nil || IsNil(o.SandboxClass.Get()) {
		var ret CreateRunnerSandboxClass
		return ret
	}
	return *o.SandboxClass.Get()
}

// GetSandboxClassOk returns a tuple with the SandboxClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateRunner) GetSandboxClassOk() (*CreateRunnerSandboxClass, bool) {
	if o == nil {
		return nil, false
	}
	return o.SandboxClass.Get(), o.SandboxClass.IsSet()
}

// HasSandboxClass returns a boolean if a field has been set.
func (o *CreateRunner) HasSandboxClass() bool {
	if o != nil && o.SandboxClass.IsSet() {
		return true
	}

	return false
}

// SetSandboxClass gets a reference to the given NullableCreateRunnerSandboxClass and assigns it to the SandboxClass field.
func (o *CreateRunner) SetSandboxClass(v CreateRunnerSandboxClass) {
	o.SandboxClass.Set(&v)
}
// SetSandboxClassNil sets the value for SandboxClass to be an explicit nil
func (o *CreateRunner) SetSandboxClassNil() {
	o.SandboxClass.Set(nil)
}

// UnsetSandboxClass ensures that no value is present for SandboxClass, not even an explicit nil
func (o *CreateRunner) UnsetSandboxClass() {
	o.SandboxClass.Unset()
}

func (o CreateRunner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRunner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionId"] = o.RegionId
	toSerialize["name"] = o.Name
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.SandboxClass.IsSet() {
		toSerialize["sandboxClass"] = o.SandboxClass.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRunner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRunner := _CreateRunner{}

	err = json.Unmarshal(data, &varCreateRunner)

	if err != nil {
		return err
	}

	*o = CreateRunner(varCreateRunner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "regionId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "sandboxClass")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRunner struct {
	value *CreateRunner
	isSet bool
}

func (v NullableCreateRunner) Get() *CreateRunner {
	return v.value
}

func (v *NullableCreateRunner) Set(val *CreateRunner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRunner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRunner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRunner(val *CreateRunner) *NullableCreateRunner {
	return &NullableCreateRunner{value: val, isSet: true}
}

func (v NullableCreateRunner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRunner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


