/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AccountProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountProvider{}

// AccountProvider struct for AccountProvider
type AccountProvider struct {
	// WorkOS identity provider, e.g. GoogleOAuth or GitHubOAuth
	Provider string `json:"provider"`
	// Human-readable provider name
	DisplayName string `json:"displayName"`
	// Whether the authenticated user has an identity from this provider
	Linked bool `json:"linked"`
	AdditionalProperties map[string]interface{}
}

type _AccountProvider AccountProvider

// NewAccountProvider instantiates a new AccountProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountProvider(provider string, displayName string, linked bool) *AccountProvider {
	this := AccountProvider{}
	this.Provider = provider
	this.DisplayName = displayName
	this.Linked = linked
	return &this
}

// NewAccountProviderWithDefaults instantiates a new AccountProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountProviderWithDefaults() *AccountProvider {
	this := AccountProvider{}
	return &this
}

// GetProvider returns the Provider field value
func (o *AccountProvider) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *AccountProvider) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *AccountProvider) SetProvider(v string) {
	o.Provider = v
}

// GetDisplayName returns the DisplayName field value
func (o *AccountProvider) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AccountProvider) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AccountProvider) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetLinked returns the Linked field value
func (o *AccountProvider) GetLinked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Linked
}

// GetLinkedOk returns a tuple with the Linked field value
// and a boolean to check if the value has been set.
func (o *AccountProvider) GetLinkedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Linked, true
}

// SetLinked sets field value
func (o *AccountProvider) SetLinked(v bool) {
	o.Linked = v
}

func (o AccountProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["displayName"] = o.DisplayName
	toSerialize["linked"] = o.Linked

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountProvider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"displayName",
		"linked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountProvider := _AccountProvider{}

	err = json.Unmarshal(data, &varAccountProvider)

	if err != nil {
		return err
	}

	*o = AccountProvider(varAccountProvider)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "provider")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "linked")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountProvider struct {
	value *AccountProvider
	isSet bool
}

func (v NullableAccountProvider) Get() *AccountProvider {
	return v.value
}

func (v *NullableAccountProvider) Set(val *AccountProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountProvider(val *AccountProvider) *NullableAccountProvider {
	return &NullableAccountProvider{value: val, isSet: true}
}

func (v NullableAccountProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


