/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SnapshotStateUpdatedWebhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotStateUpdatedWebhook{}

// SnapshotStateUpdatedWebhook struct for SnapshotStateUpdatedWebhook
type SnapshotStateUpdatedWebhook struct {
	// Event type identifier
	Event WebhookEvent `json:"event"`
	// Timestamp when the event occurred
	Timestamp time.Time `json:"timestamp"`
	// Snapshot ID
	Id string `json:"id"`
	// Snapshot name
	Name string `json:"name"`
	// Organization ID
	OrganizationId string `json:"organizationId"`
	// Previous state
	OldState SnapshotState `json:"oldState"`
	// New state
	NewState SnapshotState `json:"newState"`
	// When the snapshot was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _SnapshotStateUpdatedWebhook SnapshotStateUpdatedWebhook

// NewSnapshotStateUpdatedWebhook instantiates a new SnapshotStateUpdatedWebhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotStateUpdatedWebhook(event WebhookEvent, timestamp time.Time, id string, name string, organizationId string, oldState SnapshotState, newState SnapshotState, updatedAt time.Time) *SnapshotStateUpdatedWebhook {
	this := SnapshotStateUpdatedWebhook{}
	this.Event = event
	this.Timestamp = timestamp
	this.Id = id
	this.Name = name
	this.OrganizationId = organizationId
	this.OldState = oldState
	this.NewState = newState
	this.UpdatedAt = updatedAt
	return &this
}

// NewSnapshotStateUpdatedWebhookWithDefaults instantiates a new SnapshotStateUpdatedWebhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotStateUpdatedWebhookWithDefaults() *SnapshotStateUpdatedWebhook {
	this := SnapshotStateUpdatedWebhook{}
	return &this
}

// GetEvent returns the Event field value
func (o *SnapshotStateUpdatedWebhook) GetEvent() WebhookEvent {
	if o == nil {
		var ret WebhookEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetEventOk() (*WebhookEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *SnapshotStateUpdatedWebhook) SetEvent(v WebhookEvent) {
	o.Event = v
}

// GetTimestamp returns the Timestamp field value
func (o *SnapshotStateUpdatedWebhook) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *SnapshotStateUpdatedWebhook) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetId returns the Id field value
func (o *SnapshotStateUpdatedWebhook) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SnapshotStateUpdatedWebhook) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SnapshotStateUpdatedWebhook) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SnapshotStateUpdatedWebhook) SetName(v string) {
	o.Name = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *SnapshotStateUpdatedWebhook) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *SnapshotStateUpdatedWebhook) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetOldState returns the OldState field value
func (o *SnapshotStateUpdatedWebhook) GetOldState() SnapshotState {
	if o == nil {
		var ret SnapshotState
		return ret
	}

	return o.OldState
}

// GetOldStateOk returns a tuple with the OldState field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetOldStateOk() (*SnapshotState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldState, true
}

// SetOldState sets field value
func (o *SnapshotStateUpdatedWebhook) SetOldState(v SnapshotState) {
	o.OldState = v
}

// GetNewState returns the NewState field value
func (o *SnapshotStateUpdatedWebhook) GetNewState() SnapshotState {
	if o == nil {
		var ret SnapshotState
		return ret
	}

	return o.NewState
}

// GetNewStateOk returns a tuple with the NewState field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetNewStateOk() (*SnapshotState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewState, true
}

// SetNewState sets field value
func (o *SnapshotStateUpdatedWebhook) SetNewState(v SnapshotState) {
	o.NewState = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SnapshotStateUpdatedWebhook) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SnapshotStateUpdatedWebhook) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SnapshotStateUpdatedWebhook) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SnapshotStateUpdatedWebhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotStateUpdatedWebhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["oldState"] = o.OldState
	toSerialize["newState"] = o.NewState
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SnapshotStateUpdatedWebhook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"timestamp",
		"id",
		"name",
		"organizationId",
		"oldState",
		"newState",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnapshotStateUpdatedWebhook := _SnapshotStateUpdatedWebhook{}

	err = json.Unmarshal(data, &varSnapshotStateUpdatedWebhook)

	if err != nil {
		return err
	}

	*o = SnapshotStateUpdatedWebhook(varSnapshotStateUpdatedWebhook)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "timestamp")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "oldState")
		delete(additionalProperties, "newState")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSnapshotStateUpdatedWebhook struct {
	value *SnapshotStateUpdatedWebhook
	isSet bool
}

func (v NullableSnapshotStateUpdatedWebhook) Get() *SnapshotStateUpdatedWebhook {
	return v.value
}

func (v *NullableSnapshotStateUpdatedWebhook) Set(val *SnapshotStateUpdatedWebhook) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotStateUpdatedWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotStateUpdatedWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotStateUpdatedWebhook(val *SnapshotStateUpdatedWebhook) *NullableSnapshotStateUpdatedWebhook {
	return &NullableSnapshotStateUpdatedWebhook{value: val, isSet: true}
}

func (v NullableSnapshotStateUpdatedWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotStateUpdatedWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


