/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the WorkosSsoConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkosSsoConnection{}

// WorkosSsoConnection struct for WorkosSsoConnection
type WorkosSsoConnection struct {
	// WorkOS connection ID
	Id string `json:"id"`
	// Connection name as set in the WorkOS Admin Portal
	Name string `json:"name"`
	// WorkOS connection type, e.g. OktaSAML, AzureSAML, GenericOIDC
	ConnectionType string `json:"connectionType"`
	// WorkOS connection state: active means logins work; draft and requires_type mean setup is incomplete
	State string `json:"state"`
	// Email domains routed to this connection
	Domains []string `json:"domains"`
	// When the connection was created in WorkOS
	CreatedAt time.Time `json:"createdAt"`
	// When the connection was last changed in WorkOS
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _WorkosSsoConnection WorkosSsoConnection

// NewWorkosSsoConnection instantiates a new WorkosSsoConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkosSsoConnection(id string, name string, connectionType string, state string, domains []string, createdAt time.Time, updatedAt time.Time) *WorkosSsoConnection {
	this := WorkosSsoConnection{}
	this.Id = id
	this.Name = name
	this.ConnectionType = connectionType
	this.State = state
	this.Domains = domains
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewWorkosSsoConnectionWithDefaults instantiates a new WorkosSsoConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkosSsoConnectionWithDefaults() *WorkosSsoConnection {
	this := WorkosSsoConnection{}
	return &this
}

// GetId returns the Id field value
func (o *WorkosSsoConnection) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkosSsoConnection) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WorkosSsoConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkosSsoConnection) SetName(v string) {
	o.Name = v
}

// GetConnectionType returns the ConnectionType field value
func (o *WorkosSsoConnection) GetConnectionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionType
}

// GetConnectionTypeOk returns a tuple with the ConnectionType field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetConnectionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionType, true
}

// SetConnectionType sets field value
func (o *WorkosSsoConnection) SetConnectionType(v string) {
	o.ConnectionType = v
}

// GetState returns the State field value
func (o *WorkosSsoConnection) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WorkosSsoConnection) SetState(v string) {
	o.State = v
}

// GetDomains returns the Domains field value
func (o *WorkosSsoConnection) GetDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetDomainsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domains, true
}

// SetDomains sets field value
func (o *WorkosSsoConnection) SetDomains(v []string) {
	o.Domains = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WorkosSsoConnection) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WorkosSsoConnection) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WorkosSsoConnection) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WorkosSsoConnection) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WorkosSsoConnection) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o WorkosSsoConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkosSsoConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["connectionType"] = o.ConnectionType
	toSerialize["state"] = o.State
	toSerialize["domains"] = o.Domains
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkosSsoConnection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"connectionType",
		"state",
		"domains",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkosSsoConnection := _WorkosSsoConnection{}

	err = json.Unmarshal(data, &varWorkosSsoConnection)

	if err != nil {
		return err
	}

	*o = WorkosSsoConnection(varWorkosSsoConnection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "connectionType")
		delete(additionalProperties, "state")
		delete(additionalProperties, "domains")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkosSsoConnection struct {
	value *WorkosSsoConnection
	isSet bool
}

func (v NullableWorkosSsoConnection) Get() *WorkosSsoConnection {
	return v.value
}

func (v *NullableWorkosSsoConnection) Set(val *WorkosSsoConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkosSsoConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkosSsoConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkosSsoConnection(val *WorkosSsoConnection) *NullableWorkosSsoConnection {
	return &NullableWorkosSsoConnection{value: val, isSet: true}
}

func (v NullableWorkosSsoConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkosSsoConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


