/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the UpdateOidcIdPConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOidcIdPConfig{}

// UpdateOidcIdPConfig struct for UpdateOidcIdPConfig
type UpdateOidcIdPConfig struct {
	// OIDC Issuer URL
	IssuerUrl *string `json:"issuerUrl,omitempty"`
	// OAuth Client ID
	ClientId *string `json:"clientId,omitempty"`
	// OAuth Client Secret
	ClientSecret *string `json:"clientSecret,omitempty"`
	// OAuth scopes
	Scope *string `json:"scope,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateOidcIdPConfig UpdateOidcIdPConfig

// NewUpdateOidcIdPConfig instantiates a new UpdateOidcIdPConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOidcIdPConfig() *UpdateOidcIdPConfig {
	this := UpdateOidcIdPConfig{}
	return &this
}

// NewUpdateOidcIdPConfigWithDefaults instantiates a new UpdateOidcIdPConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOidcIdPConfigWithDefaults() *UpdateOidcIdPConfig {
	this := UpdateOidcIdPConfig{}
	return &this
}

// GetIssuerUrl returns the IssuerUrl field value if set, zero value otherwise.
func (o *UpdateOidcIdPConfig) GetIssuerUrl() string {
	if o == nil || IsNil(o.IssuerUrl) {
		var ret string
		return ret
	}
	return *o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOidcIdPConfig) GetIssuerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IssuerUrl) {
		return nil, false
	}
	return o.IssuerUrl, true
}

// HasIssuerUrl returns a boolean if a field has been set.
func (o *UpdateOidcIdPConfig) HasIssuerUrl() bool {
	if o != nil && !IsNil(o.IssuerUrl) {
		return true
	}

	return false
}

// SetIssuerUrl gets a reference to the given string and assigns it to the IssuerUrl field.
func (o *UpdateOidcIdPConfig) SetIssuerUrl(v string) {
	o.IssuerUrl = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *UpdateOidcIdPConfig) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOidcIdPConfig) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *UpdateOidcIdPConfig) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *UpdateOidcIdPConfig) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *UpdateOidcIdPConfig) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOidcIdPConfig) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *UpdateOidcIdPConfig) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *UpdateOidcIdPConfig) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *UpdateOidcIdPConfig) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOidcIdPConfig) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *UpdateOidcIdPConfig) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *UpdateOidcIdPConfig) SetScope(v string) {
	o.Scope = &v
}

func (o UpdateOidcIdPConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOidcIdPConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IssuerUrl) {
		toSerialize["issuerUrl"] = o.IssuerUrl
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateOidcIdPConfig) UnmarshalJSON(data []byte) (err error) {
	varUpdateOidcIdPConfig := _UpdateOidcIdPConfig{}

	err = json.Unmarshal(data, &varUpdateOidcIdPConfig)

	if err != nil {
		return err
	}

	*o = UpdateOidcIdPConfig(varUpdateOidcIdPConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "issuerUrl")
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "clientSecret")
		delete(additionalProperties, "scope")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateOidcIdPConfig struct {
	value *UpdateOidcIdPConfig
	isSet bool
}

func (v NullableUpdateOidcIdPConfig) Get() *UpdateOidcIdPConfig {
	return v.value
}

func (v *NullableUpdateOidcIdPConfig) Set(val *UpdateOidcIdPConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOidcIdPConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOidcIdPConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOidcIdPConfig(val *UpdateOidcIdPConfig) *NullableUpdateOidcIdPConfig {
	return &NullableUpdateOidcIdPConfig{value: val, isSet: true}
}

func (v NullableUpdateOidcIdPConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOidcIdPConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


