=begin
#Daytona

#Daytona AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: support@daytona.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module DaytonaApiClient
  class SecretApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create secret
    # @param create_secret [CreateSecret] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Secret]
    def create_secret(create_secret, opts = {})
      data, _status_code, _headers = create_secret_with_http_info(create_secret, opts)
      data
    end

    # Create secret
    # @param create_secret [CreateSecret] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<(Secret, Integer, Hash)>] Secret data, response status code and response headers
    def create_secret_with_http_info(create_secret, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecretApi.create_secret ...'
      end
      # verify the required parameter 'create_secret' is set
      if @api_client.config.client_side_validation && create_secret.nil?
        fail ArgumentError, "Missing the required parameter 'create_secret' when calling SecretApi.create_secret"
      end
      # resource path
      local_var_path = '/secret'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Daytona-Organization-ID'] = opts[:'x_daytona_organization_id'] if !opts[:'x_daytona_organization_id'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_secret)

      # return_type
      return_type = opts[:debug_return_type] || 'Secret'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"SecretApi.create_secret",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecretApi#create_secret\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete secret
    # @param secret_id [String] ID of the secret
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [nil]
    def delete_secret(secret_id, opts = {})
      delete_secret_with_http_info(secret_id, opts)
      nil
    end

    # Delete secret
    # @param secret_id [String] ID of the secret
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_secret_with_http_info(secret_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecretApi.delete_secret ...'
      end
      # verify the required parameter 'secret_id' is set
      if @api_client.config.client_side_validation && secret_id.nil?
        fail ArgumentError, "Missing the required parameter 'secret_id' when calling SecretApi.delete_secret"
      end
      # resource path
      local_var_path = '/secret/{secretId}'.sub('{' + 'secretId' + '}', CGI.escape(secret_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      header_params[:'X-Daytona-Organization-ID'] = opts[:'x_daytona_organization_id'] if !opts[:'x_daytona_organization_id'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"SecretApi.delete_secret",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecretApi#delete_secret\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get secret
    # @param secret_id [String] ID of the secret
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Secret]
    def get_secret(secret_id, opts = {})
      data, _status_code, _headers = get_secret_with_http_info(secret_id, opts)
      data
    end

    # Get secret
    # @param secret_id [String] ID of the secret
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<(Secret, Integer, Hash)>] Secret data, response status code and response headers
    def get_secret_with_http_info(secret_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecretApi.get_secret ...'
      end
      # verify the required parameter 'secret_id' is set
      if @api_client.config.client_side_validation && secret_id.nil?
        fail ArgumentError, "Missing the required parameter 'secret_id' when calling SecretApi.get_secret"
      end
      # resource path
      local_var_path = '/secret/{secretId}'.sub('{' + 'secretId' + '}', CGI.escape(secret_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Daytona-Organization-ID'] = opts[:'x_daytona_organization_id'] if !opts[:'x_daytona_organization_id'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Secret'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"SecretApi.get_secret",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecretApi#get_secret\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List secrets
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<Secret>]
    def list_secrets(opts = {})
      data, _status_code, _headers = list_secrets_with_http_info(opts)
      data
    end

    # List secrets
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<(Array<Secret>, Integer, Hash)>] Array<Secret> data, response status code and response headers
    def list_secrets_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecretApi.list_secrets ...'
      end
      # resource path
      local_var_path = '/secret'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Daytona-Organization-ID'] = opts[:'x_daytona_organization_id'] if !opts[:'x_daytona_organization_id'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Secret>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"SecretApi.list_secrets",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecretApi#list_secrets\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update secret
    # @param secret_id [String] ID of the secret
    # @param update_secret [UpdateSecret] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Secret]
    def update_secret(secret_id, update_secret, opts = {})
      data, _status_code, _headers = update_secret_with_http_info(secret_id, update_secret, opts)
      data
    end

    # Update secret
    # @param secret_id [String] ID of the secret
    # @param update_secret [UpdateSecret] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_daytona_organization_id Use with JWT to specify the organization ID
    # @return [Array<(Secret, Integer, Hash)>] Secret data, response status code and response headers
    def update_secret_with_http_info(secret_id, update_secret, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SecretApi.update_secret ...'
      end
      # verify the required parameter 'secret_id' is set
      if @api_client.config.client_side_validation && secret_id.nil?
        fail ArgumentError, "Missing the required parameter 'secret_id' when calling SecretApi.update_secret"
      end
      # verify the required parameter 'update_secret' is set
      if @api_client.config.client_side_validation && update_secret.nil?
        fail ArgumentError, "Missing the required parameter 'update_secret' when calling SecretApi.update_secret"
      end
      # resource path
      local_var_path = '/secret/{secretId}'.sub('{' + 'secretId' + '}', CGI.escape(secret_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Daytona-Organization-ID'] = opts[:'x_daytona_organization_id'] if !opts[:'x_daytona_organization_id'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(update_secret)

      # return_type
      return_type = opts[:debug_return_type] || 'Secret'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearer', 'oauth2']

      new_options = opts.merge(
        :operation => :"SecretApi.update_secret",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SecretApi#update_secret\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
